### PR TITLE
Refactor PDO wrapper

### PR DESCRIPTION
**Pull request by petk**
Some concerns were raised on the mailing list that this PHP application doesn't need a PDO wrapper at all. This is a work in progress to refactor this PDO wrapper a bit...

Changes so far:
- ::fetchRow() method removed in favor of the vanilla PDOStatement::fetch()
- ::fetchAll() override removed in favor of the vanilla
  PDOStatement::fetchAll()
- ::fetchCol() removed since it is not used and is only a wrapper for
  the PDOStatement::fetchColumn()
- PDO fetch_style synced accross the app. When no fetch style is passed
  the default PDO::FETCH_ASSOC is used as set when connecting to db.

Other things coming up soon...

### CODE REVIEW

**Comment by KalleZ** [comment]
I like this PR a lot, thanks for your work Peter (I was gonna try beat you to it)!

 * ::fetchOne() method is only used 9 times and should be easy to migrate too. Looking at the grep output for it, it seems that all of them should only ever return one result so calling any of the fetch() methods without the array dereferencing syntax should do it
 * I see a few places where the execute() method is not called with chaining (from the diff of this PR), since there already seems to be a fair diversity between the two call syntaxes, what do you think about simply getting rid of the chaining (I admit, I do prefer chaining myself too)

For the remaining two methods of \App\Database\Database:

 * If we end up with removing the execute() method of \App\Database\Statement, then the class is redudant and thrus making the __construct() call entirely redudant (if not, then the ::setAttribute() call can be moved to the prepend file to prevent overloading the PDO constructor).
 * I'm a little uncertain about how we can properly deal with the ::escape() method here, I do agree the behavior is kinda odd and should be hidden behind a function:

`function esc($dbh, $input) {
 return(substr($dbh->quote($input), 1, -1));
}`

What do you think Peter?

**Comment by petk** [comment]
* `::fetchOne()` method removed (such methods should probably be used in repositories or in the code directly)
* `escapeSQL()` function removed (functions are bad by default in such apps because testing can't be done properly due to a global $dbh usage and it goes away from good OOP practices not to mention the wrapping functionality around the `PDO::quote()` belongs more to a wrapper or at least to a utility class of some sort).

Which now leaves only that Statement class with the overridden `execute` method. Since chaining is used practically everywhere in this app, I'd leave it be. It will introduce too many changes for the time being. Or at least until further refactoring across the app can be done. It's good feature except that the complete overriding of already implemented vanilla PHP method can't fully be done.

PDO can be directly created with `new \PDO(...)` in the bootstrap file (prepend.php) as it is or via the app container or some other unplanned feature currently that we're not aware yet. Which will all work ok, I think. We can go into this direction at the moment and see where this fails with new features in the future.

Every step away from the vanilla PDO will be opinionated matter. Yet, people still invent wrappers everywhere which isn't surprising. Wrapping things makes apps better and less dependent on outside inconsistencies or simply because they need new features.

We certainly don't want to reinvent an ORM here, nor we want to invent a too complex PDO wrapper/database layer abstraction because understanding app architecture is still more important than complexity and flexibility for site maintainers. All that is certain and future proof enough. However, with such a large number of queries everywhere, removal of the main PDO wrapper it is something to think about.

The only feature this app might be missing with the removal of the PDO wrapper class is adding new features such as `::run()` method that can be used on the majority of the queries in the app. (Note, that such method is also the most used approach across all wrappers out there).

Vanilla PDO example:

```php
// ...
$id = $_GET['id'] ?? 1;
$sql = 'SELECT title FROM articles WHERE id = ?';
$statement = $dbh->prepare($sql);
$exec = $statement->execute([$id]);
$article = $statement->fetch();
```

With currently integrated chaining additionally this is possible (with vanilla PDO it isn't):

```php
$id = $_GET['id'] ?? 1;
$sql = 'SELECT title FROM articles WHERE id = ?';
$statement = $dbh->prepare($sql)->execute([$id]);
$article = $statement->fetch();
```

Which can be further extended into a one liner call:

```php
$id = $_GET['id'] ?? 1;
$sql = 'SELECT title FROM articles WHERE id = ?';
$article = $dbh->prepare($sql)->execute([$id])->fetch();
```

What PDO wrappers direction probably should be more about than only overriding a vanilla `PDOStatement::execute()` method, is adding something like this:

```php
$id = $_GET['id'] ?? 1;
$sql = 'SELECT title FROM articles WHERE id = ?';
$article = $dbh->run($sql, [$id])->fetch();
```

The `::run()` method:

```php
class Database
{
    // ...

    /**
     * Runs given SQL query using prepared statements or query method.
     */
    public function run(string $sql, array $arguments = []): \PDOStatement
    {
        if (!$arguments) {
             return $this->adapter->query($sql);
        }

        $statement = $this->adapter->prepare($sql);
        $statement->execute($arguments);

        return $statement;
    }
}
```

Which is a better approach, it's up to this site maintainers to decide... I'll do some more checkups here until this pull request is ready to go...

**Comment by KalleZ** [comment]
Hi Peter! Thanks a lot for your work. I greatly appreciate it and I think you should commit it as is, then I can take a look at the rest if I manage to reconfigure it on Windows (as I recently moved system, setting up everything is a bit time consuming).

I agree that it is much "nicer", however there is just something logically wrong about creating a wrapper for a wrapper imho. If the API is poor or annoying, then I believe the actual wrapper should be fixed in the first place, and I'm pretty certain that updates to PDO would be welcomed as commits to it is sort of rare, at least its core part. I think there is also another opinion regarding this matter, which is why I initially raised the concern on the mailing lists. If even we ourselves, PHP.net, makes a wrapper for a core component we ship with the language, it does send a bad indicator that we acknowledge its design is poor, but I think thats perhaps enough for another discussion for PDO itself, I think I remember enough PDO internals for us to be able to do an RFC together for such if you are interested at one point.

**Comment by petk** [comment]
Fair enough... Then PDO sounds very noble planned if such approaches should be done and it should cover more use cases out there.

PDO wrapper removed via above commit into a vanilla PDO connection only and now has only that Statement class and execute method...

Personally, I don't see extending PDO functionality a matter of a poor PDO design actually. PDO is designed with certain approach in mind and has functionality that is currently used out there. And each project with database has its own specifics.

If mentioned new features should be added to PDO itself in the PHP core or to look into this more, this definitely sounds promising. But again, this particular pull request shouldn't be a metric what is the best PDO usage practice to be extended into a RFC for the PDO itself. Or that every other project should follow this. There are way too many parameters that influence these things. It's a simple usage for a very specific project of a bugs.php.net app that is need of improvements and some bug fixes...

**Comment by petk** [comment]
If there are no objections, I'll merge this one since PDO can be used without a separate database class wrapping it for now. It if will cause some issues in the future we can reintroduce a new wrapper again. Either due to verbosity reasons or to introduce some other database etc.

**Pull request merged**
