### PR TITLE
Append PHP-7.4 dev branch to the versions list

### PR DESCRIPTION
**Pull request by petk**
Hello, this now appends also upcoming PHP-7.4 dev branch to the list of PHP versions.

However, goal here is to improve this one step further - versions selection is not so much logical because not so many people even know what snaps mean. So this would also remove the "snap" term from the selection and only "Git" would be visible.

A quick "wireframe"/concept: https://petk.github.io/testing/bugs.php.net/report-bug-2.html

Screenshot 2019-05-22 at 03 43 35

### CODE REVIEW

**Comment by cmb69** [comment]
"snaps" may be relevant for Windows; see https://windows.php.net/downloads/snaps/. Maybe say "GIt/snap" or so?

**Comment by petk** [comment]
Thank you for the explanation. Maybe we should then say specifically something like "windows snap" here? Because there are no other snapshots of PHP out there in the *.php.net context so far anymore.

**Comment by cmb69** [comment]
Indeed, the Linux snaps are long gone, so saying "Windows snaps" is fine, I think. Thanks!

**Comment by petk** [comment]
(offtopic but for a reason comment)
@KalleZ, similar concern is here. Please see this: http://news.php.net/php.webmaster/27799

So, I think that you won't mind that some changes are done based on practical experience a bit also...

**Pull request closed without merging**
