### PR TITLE
Convert to Composer project

### PR DESCRIPTION
**Pull request by kelunik**
Makes it installable via `composer install` and dependencies compatible with PHP 7.

### CODE REVIEW

**Comment by salathe** [comment]
The README needs an update for this PR.  On the whole, anything which makes it easier to get a development bugsweb up and running gets a thumbs up from me.

**Comment by kelunik** [comment]
Composer needs to be recent for it to work, because something with PEAR changed, see https://github.com/composer/composer/issues/6193.

@salathe What do you think about https://github.com/php/web-bugs/pull/27/files#diff-adfab6c305dfaea7341720780766a803R50? Can we require Composer to be used also for the production deployment? I think the deploy scripts need an update then.

**Comment by heiglandreas** [comment]
*Recent* meaning at least which version? And is there a way to only allow a certain composer-version to update/install the packages? Like ```require composer/composer ^1.*```?

**Comment by kelunik** [comment]
@heiglandreas I guess 1.3. https://github.com/composer/composer/pull/6202

**Comment by petk** [comment]
Hello,
few additional changes have been done via recent commits in this repository. The MDB2 dependency is no longer required. So only PHP vanilla PDO is used at the moment.

All these can be removed now:
- pear-pear.php.net/mdb2
- pear-pear.php.net/mdb2_driver_mysqli
- pear-pear.php.net/db_dataobject
- cweagans/composer-patches
- and all the attached patches

Composer should be then part of the [deployment process](https://github.com/php/systems/blob/master/update-bugsweb, as well yes. However, I've just recently started checking the deployment parts of the php sites, so I'm not the one that can do that.

Another nice to have thing here would be an enabled travis for this repository and usage of the PHPUnit testing (installation also done via Composer)...

**Comment by petk** [comment]
This patch has been applied via 83d6860af9a4554a234177d1d38f37907fcb4b4f and adjusted a bit to start integrating possible development dependencies and list required PHP version with extensions in multiple steps.

Pear packages are at the time of this writing still required to be installed via pear CLI script.

Thanks.

**Comment by php-pulls** [comment]
**Comment on behalf of petk at php.net:**

Applied via 83d6860af9a4554a234177d1d38f37907fcb4b4f

**Pull request closed without merging**
