### PR TITLE
Bug #68801 	Edit button shall not show up if the logged in user is not the reporter

### PR DESCRIPTION
**Pull request by humanoyd**
Hide the Edit button, if the Logged in user is not the reporter, because if the logged in user is not the reporter he wont be able to use this tab anyway.

### CODE REVIEW

**Comment by Sobak** [comment]
Looks good to me, but you should squash two commits together, I think.

**Comment by humanoyd** [comment]
Squashed

**Comment by Sobak** [comment]
And merged, thanks!

**Comment by humanoyd** [comment]
Thanks for the quick response

**Pull request merged**
