### PR TITLE
debug builds are not required for GDB

### PR DESCRIPTION
**Pull request by remicollet**
https://news-web.php.net/php.internals/121036

### CODE REVIEW

**Review by Girgias — APPROVED** [review]

**Comment by remicollet** [comment]
@Girgias thanks

**Comment by iluuu1994** [comment]
It's worth noting that there are some benefits to a debug build:

* Assertions may help identify invalid state earlier
* It may provide a more accurate stack trace
* It may avoid incorrect optimizations due to undefined behavior

Can one obtain a non-stripped binary from apt/dnf/etc.? If not and PHP needs to be built manually anyway, building with debug might be preferable, as long as it's not used in production. If production is necessary, we may mention that `./configure --disable-debug CFLAGS="-g"` can be used to retain debug symbols.

**Comment by remicollet** [comment]
> Assertions may help identify invalid state earlier

Yes, so the reason why I say it is more for PHP and extensions dev than for other users

There have been some questions recently because of people using debug build for a bad reason
Ex: https://github.com/php-amqp/php-amqp/pull/486#issuecomment-1713294518

> Can one obtain a non-stripped binary from apt/dnf/etc

Yes, for RPM by installing the `debuginfo` and `debugsource` packages (generated during the build, providing extracted debug symbols).

GDB is even able to list missing ones and give command to install them, ex
```
$ gdb php83
...
Reading symbols from .gnu_debugdata for /opt/remi/php83/root/usr/bin/php...
(No debugging symbols found in .gnu_debugdata for /opt/remi/php83/root/usr/bin/php)
Missing separate debuginfos, use: dnf debuginfo-install php83-php-cli-8.3.0~rc1-1.fc37.remi.x86_64
```

Other Linux distro probably have same kind of feature.

**Comment by iluuu1994** [comment]
> There have been some questions recently because of people using debug build for a bad reason

I'm not sure this is a bad reason, per se. The `assert` was buggy, and can also lead to incorrect optimizations (e.g. removal of `if (ptr == NULL) {` branches.

> GDB is even able to list missing ones and give command to install them, ex

Ah, that's nice!

**Comment by remicollet** [comment]
> I'm not sure this is a bad reason, per see. 

Ok, so we disagree ;)

**Pull request merged**
