### PR TITLE
Remove PHP 5.6 and add PHP 7.4 to "Common searches" list

### PR DESCRIPTION
**Pull request by carusogabriel**
Remove the PHP 5.6 as isn't support anymore, and add PHP 7.4 as it was already branched and people can start to fill bugs for this version.

### CODE REVIEW

**Comment by petk** [comment]
PHP 7.4 and master branches are now something new, yes. This should then be somehow refactored also on the bug report page itself so the PHP-7.4 branch can even be selected in the first place:
https://bugs.php.net/report.php
screenshot 2019-02-10 at 23 25 58

**Comment by carusogabriel** [comment]
@petk Thanks, I'll be updating this patch then.

**Comment by petk** [comment]
I'm also thinking that these versions selection box need to be refactored.

Something like this:
https://petk.github.io/testing/bugs.php.net/report-bug-2.html

Snaps is confusing term because it is not used anymore, however Windows snapshots are used. I'll recheck it out...

**Comment by petk** [comment]
So, this won't take too long, I've merged the PHP 5.6 removal in the master via 7e3870ef1573374f55db5204bf968274f75e1ad0. Thank you @carusogabriel 

About adding the PHP 7.4 branch, I think first step would be to sort out these versions. Which ones are important, and which are not anymore (on the bug reporting and search pages)... Yes, PHP 7.4 really need to be selectable in these forms. That's for sure.

The [discussion](http://news.php.net/php.webmaster/27799) hasn't moved forward yet (I think people there are simply too busy for any kind of work on the websites), so I'll just go ahead and prepare something to work with. Stay tuned... Thanks.

**Comment by php-pulls** [comment]
**Comment on behalf of petk at php.net:**

Partially applied via 7e3870ef1573374f55db5204bf968274f75e1ad0

**Pull request closed without merging**
