### PR TITLE
Converted the current admin pages (/admin) to use proper templates

### PR DESCRIPTION
**Pull request by PeeHaa**
Rewrote the admin pages to use proper templating and implement repositories for data retrieval

### CODE REVIEW

**Comment by petk** [comment]
Very neat. Let me go through this one... Thank you for your help @PeeHaa

**Comment by petk** [comment]
@KalleZ this one will be merged today if all checks are ok from my side...

**Comment by KalleZ** [comment]
@petk Looks good to me. I think once this is merged we can also remove the dynamic table functions which I added for the mysql information pages (as I do not believe they are used anywhere else).

**Comment by php-pulls** [comment]
**Comment on behalf of petk at php.net:**

Applied via 9531cd154db3a5e41b6e806226e9e371d2699f52

**Comment by petk** [comment]
Applied via 9531cd154db3a5e41b6e806226e9e371d2699f52 

I've only improved the Context's include method a bit on the way and the menu conditionals. In templates usually less global scope the better...

Thank you @PeeHaa for this update 🎉

**Comment by petk** [comment]
Unused functions removed via 95cdd55d51122c8ba26f6a9db7decfc1682a40cd thank you @KalleZ for the info 👍

**Pull request closed without merging**
