### PR TITLE
Follow Meta->Link->Next on github jsonp in order to fetch all PHP repos.

### PR DESCRIPTION
**Pull request by jabiinfante**
When adding a pull request to a reported bug, only the first page from Github jsonp is loaded, so many repos are not listed.

This PR would make recursive calls, in order to fetch all PHP repos, and fill the select control with them.

### CODE REVIEW

**Comment by sethbattin** [comment]
I looked at this PR after the wide cast from Sara via twitter, and all seems well to me.  The code seems to match the docs (https://developer.github.com/v3/#pagination) as well as the data:

image

One concern due to lack of experience by me: do the jquery jsonp query params need to be stripped from the urls after the first call?  Similar question, does this API call need to be jsonp at all?  @jabiinfante can probably confirm or deny.

One possible improvement would be to use the `per_page` parameter's maximum value of 100 rather than the default 30.  Fewer total calls might obviate the need for iterating over pages for the time being.

**Comment by sgolemon** [comment]
Good point about `per_page`.  Looking further down the JS file, I see the pull request drop down is populated exactly this way.

Will give @jabiinfante a chance to chime in, but personally I don't mind doing that as a much lighter touch solution that has the added benefit of reducing API calls.

**Comment by jabiinfante** [comment]
OK. Just added `per_page` parameter and squashed to one commit.

@sethbattin after the first call, the method is recalled with the URL given by the gh api, so there is no need to strip any other param. 

Also, JSONP is not required, since github response has got `Access-Control-Allow-Origin:*`... Allthought the `Link` Header should be parsed in order to follow the next pages (if any). With JSONP, that information is given in the response body, and it's more easily parseable...

Is it worth making the change?

**Comment by jabiinfante** [comment]
Sorry for the delay! I've had some spare time today, and remember anout this...

I have removed the jsonp call, in favor of plain **json** (since github's Access-Control-Allow-Origin is "*"). I use the pagination information right from the header.

Also I use `per_page=100` parameter in both calls; but checking in both cases if there more than 100 items, in which case a new call(s) would be made recursively (no need to it yet).

**Comment by heiglandreas** [comment]
👍

**Comment by johannes** [comment]
I've pulled it in, should be live in about an hour.

I expect the drop-down of repos to become quite huge. If anybody has a good idea about a nicer UI which allows quickly selecting by category (php-src ideally one click, then group by pecl-*, web-* etc.) this would be great.

**Pull request merged**
