### PR TITLE
make multiple selects resizable

### PR DESCRIPTION
**Pull request by peterdd**
Just wanted report a bug on bugs.php.net, but letting the user scroll 460 entries (optgroups+options) in a 6 line height tiny multiselect in the bug search is torture.

### CODE REVIEW

**Comment by peterdd** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/resize

**Comment by cmb69** [comment]
I agree that the current solution is … suboptimal, but `resize:both` would not work for me (Chrome on Windows) for the [developer tab](https://bugs.php.net/bug.php?id=79001&edit=1). Could that be solved as well?

**Comment by peterdd** [comment]
For the single selects on the bug view developer tab like https://bugs.php.net/bug.php?id=79001&edit=1 the resizing edge grip of resize:both can be triggered by setting a size attribute >1 for the select tag.

```html
<select name="in[package_name]" size="10">
...
```

Current browsers:
Firefox: yes
Chrome: yes
Safari: no resizer shown

**Comment by cmb69** [comment]
Ah, thanks! Not really what I had hoped for, though. Maybe leave this select element untouched, but still "fix" the others (namely, the ones on report.php)?

What do others think about this?

**Comment by peterdd** [comment]
Another idea is to show the 2 big selects side by side. As both selects have same option items, the user has a better overview comparing selections.

On small displays the selects just wrap.
grafik


green/red bg just made to see the html structure.

**Comment by peterdd** [comment]
Why not just accept this tiny PR?

If you really fear side effects on other pages change it 
to

```css
#asearch select {
    resize:both;
}
```

Another improvement could be to replace the 2 selects by only 1 select and add a NOT checkbox.
Selecting many (e.g. all) easily hits the 

```
Request-URI Too Long

The requested URL's length exceeds the capacity limit for this server.
Apache/2.4.25 (Debian) Server at bugs.php.net Port 443
```

**Comment by kelunik** [comment]
IMO this should be changed to a smart select with a search, so we can also define aliases, etc.

**Comment by cmb69** [comment]
> so we can also define aliases

That would be great, but currently we don't even have categories for stuff which exists for many years; these entries need to be made in the database, and only few have access to that.

**Comment by peterdd** [comment]
Probably, but this tiny ready PR would just help immediatly.

There is **A LOT** to improve on the search, but with little improvements I hope to be accepted faster.

Experimenting with the Search form:
flexibleadvancedsearch

Get a view on the grown non-normalized DB schema:
budgb_schema_202108

**Comment by peterdd** [comment]
Please! How you guys use the bug tracker instead???

Whenever I want to search I have to open the browser developer tools and either add the 

`#asearch select{resize: both;}`

or change the size from 6 to 100 to see and select a bug/issue category/package.
phpbgselect

This quickfix makes the search human usable immediatly, at least on desktop monitors.

I know there are deeper issues with having such long selects like 
phpbgrequesttoolong
when choosing many/all options

but this PR mitigates the current situation **now**.

**Comment by cmb69** [comment]
I agree that this is an improvement, and that perfect is the enemy of good. So thanks for the PR!

**Pull request merged**
